lsi: false
safe: true
markdown: kramdown
highlighter: rouge

title: ls -lt
description: J'entrepose ici mes découvertes linux, bash, python et java que je souhaite partager et mettre de côté...
author: "Jean-François Giraud"
blog: on
#excerpt_separator: <!-- readmore -->

paginate: 25

permalink: "/blog/article/:year/:month/:day/:title/"
theme: jekyll-theme-hacker
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
paginate_path: "/blog/page/:num/"