theme: jekyll-theme-hacker
markdown: kramdown
highlighter: rouge
title: mezalor$ ls -lt
description: J'entrepose ici mes découvertes linux, bash, python et java que je souhaite partager et mettre de côté...
author: "Jean-François Giraud"
blog: on
