baseURL = 'http://example.org/'
languageCode = "fr"
defaultContentLanguage = "fr"
title = 'jfgiraud.github.io'
theme = 'hugo-ficurinia'

[params]
    author = 'Jean-François Giraud'
    description = 'J’entrepose ici mes découvertes linux, bash, python et java que je souhaite partager et mettre de côté...'
    titleFontSizeMultiplier = 1
    mainFontSizeMultiplier = 1
    monoFontSizeMultiplier = 1

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/jfgiraud"
        weight = 10
    [[menu.icons]]
        identifier = "gitlab"
        name = "GitLab"
        url = "https://gitlab.com/jfgiraud"
        weight = 10
    [[menu.icons]]
        identifier = "linkedin"
        name = "linkedin"
        url = "https://www.linkedin.com/in/jean-fran%C3%A7ois-giraud-23815318/"
        weight = 10

