version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:

    python_app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
              USER_UID: ${USER_UID}
              USER_GID: ${USER_GID}
              USER_NAME: ${USER_NAME}
              USER_PASSWORD: ${USER_PASSWORD}
              ROOT_PASSWORD: ${ROOT_PASSWORD}
        user: ${USER_NAME}
        volumes:
            - ./:/app
        command:
            tail -f /dev/null

    jekyll:
        image: jekyll/jekyll
        command: jekyll serve --watch --incremental
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll

