version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:

    python_app:
        user: $DOCKER_USER
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        command:
            tail -f /dev/null
